### POST request to add cluster
POST http://dev.idhan:16609/clusters/add
Authorization: {{idhan_key}}
Content-Type: application/json

{
  "readonly": true,
  "name": "string",
  "path": "/media",
  "size": {
    "limit": 0
  },
  "ratio": 1,
  "type": "All"
}
> {%
    // Capture cluster_id to use in next query
    client.global.set("cluster_id", response.body.jsonPath("$.cluster_id"))
%}

### Start cluster sync
POST http://dev.idhan:16609/clusters/{{cluster_id}}/scan?adopt_orphans=true&scan_mime=true&scan_metadata=true&
    stop_on_fail=false
Authorization: {{idhan_key}}
