//
// Created by kj16609 on 11/10/25.
//
#pragma once
#include <string>
#include <unordered_map>

#include "hydrus/HydrusConstants_gen.hpp"

static const std::unordered_map< std::string_view, int > hy_type_mime {
	{ "unknown", idhan::hydrus::gen_constants::APPLICATION_HYDRUS_CLIENT_COLLECTION },
	{ "image/jpeg", idhan::hydrus::gen_constants::IMAGE_JPEG },
	{ "image/png", idhan::hydrus::gen_constants::IMAGE_PNG },
	{ "image/gif", idhan::hydrus::gen_constants::ANIMATION_GIF },
	{ "image/bmp", idhan::hydrus::gen_constants::IMAGE_BMP },
	{ "application/x-shockwave-flash", idhan::hydrus::gen_constants::APPLICATION_FLASH },
	{ "application/yaml", idhan::hydrus::gen_constants::APPLICATION_YAML },
	{ "image/x-icon", idhan::hydrus::gen_constants::IMAGE_ICON },
	{ "text/html", idhan::hydrus::gen_constants::TEXT_HTML },
	{ "video/x-flv", idhan::hydrus::gen_constants::VIDEO_FLV },
	{ "application/pdf", idhan::hydrus::gen_constants::APPLICATION_PDF },
	{ "application/zip", idhan::hydrus::gen_constants::APPLICATION_ZIP },
	{ "unknown", idhan::hydrus::gen_constants::APPLICATION_HYDRUS_ENCRYPTED_ZIP },
	{ "audio/mpeg", idhan::hydrus::gen_constants::AUDIO_MP3 },
	{ "video/mp4", idhan::hydrus::gen_constants::VIDEO_MP4 },
	{ "audio/ogg", idhan::hydrus::gen_constants::AUDIO_OGG },
	{ "audio/flac", idhan::hydrus::gen_constants::AUDIO_FLAC },
	{ "audio/x-ms-wma", idhan::hydrus::gen_constants::AUDIO_WMA },
	{ "video/x-ms-wmv", idhan::hydrus::gen_constants::VIDEO_WMV },
	{ "unknown", idhan::hydrus::gen_constants::UNDETERMINED_WM },
	{ "video/x-matroska", idhan::hydrus::gen_constants::VIDEO_MKV },
	{ "video/webm", idhan::hydrus::gen_constants::VIDEO_WEBM },
	{ "application/json", idhan::hydrus::gen_constants::APPLICATION_JSON },
	{ "image/apng", idhan::hydrus::gen_constants::ANIMATION_APNG },
	{ "unknown", idhan::hydrus::gen_constants::UNDETERMINED_PNG },
	{ "video/mpeg", idhan::hydrus::gen_constants::VIDEO_MPEG },
	{ "video/quicktime", idhan::hydrus::gen_constants::VIDEO_MOV },
	{ "video/x-msvideo", idhan::hydrus::gen_constants::VIDEO_AVI },
	{ "unknown", idhan::hydrus::gen_constants::APPLICATION_HYDRUS_UPDATE_DEFINITIONS },
	{ "unknown", idhan::hydrus::gen_constants::APPLICATION_HYDRUS_UPDATE_CONTENT },
	{ "text/plain", idhan::hydrus::gen_constants::TEXT_PLAIN },
	{ "application/x-rar-compressed", idhan::hydrus::gen_constants::APPLICATION_RAR },
	{ "application/x-7z-compressed", idhan::hydrus::gen_constants::APPLICATION_7Z },
	{ "image/webp", idhan::hydrus::gen_constants::IMAGE_WEBP },
	{ "image/tiff", idhan::hydrus::gen_constants::IMAGE_TIFF },
	{ "image/vnd.adobe.photoshop", idhan::hydrus::gen_constants::APPLICATION_PSD },
	{ "audio/mp4", idhan::hydrus::gen_constants::AUDIO_M4A },
	{ "video/x-pn-realvideo", idhan::hydrus::gen_constants::VIDEO_REALMEDIA },
	{ "audio/x-pn-realaudio", idhan::hydrus::gen_constants::AUDIO_REALMEDIA },
	{ "audio/x-tta", idhan::hydrus::gen_constants::AUDIO_TRUEAUDIO },
	{ "audio/*", idhan::hydrus::gen_constants::GENERAL_AUDIO },
	{ "image/*", idhan::hydrus::gen_constants::GENERAL_IMAGE },
	{ "video/*", idhan::hydrus::gen_constants::GENERAL_VIDEO },
	{ "application/*", idhan::hydrus::gen_constants::GENERAL_APPLICATION },
	{ "unknown", idhan::hydrus::gen_constants::GENERAL_ANIMATION },
	{ "unknown", idhan::hydrus::gen_constants::APPLICATION_CLIP },
	{ "audio/x-wav", idhan::hydrus::gen_constants::AUDIO_WAVE },
	{ "video/ogg", idhan::hydrus::gen_constants::VIDEO_OGV },
	{ "audio/x-matroska", idhan::hydrus::gen_constants::AUDIO_MKV },
	{ "audio/mp4", idhan::hydrus::gen_constants::AUDIO_MP4 },
	{ "unknown", idhan::hydrus::gen_constants::UNDETERMINED_MP4 },
	{ "application/cbor", idhan::hydrus::gen_constants::APPLICATION_CBOR },
	{ "application/x-msdownload", idhan::hydrus::gen_constants::APPLICATION_WINDOWS_EXE },
	{ "audio/x-wavpack", idhan::hydrus::gen_constants::AUDIO_WAVPACK },
	{ "unknown", idhan::hydrus::gen_constants::APPLICATION_SAI2 },
	{ "application/x-krita", idhan::hydrus::gen_constants::APPLICATION_KRITA },
	{ "image/svg+xml", idhan::hydrus::gen_constants::IMAGE_SVG },
	{ "image/x-xcf", idhan::hydrus::gen_constants::APPLICATION_XCF },
	{ "application/gzip", idhan::hydrus::gen_constants::APPLICATION_GZIP },
	{ "application/x-archive", idhan::hydrus::gen_constants::GENERAL_APPLICATION_ARCHIVE },
	{ "unknown", idhan::hydrus::gen_constants::GENERAL_IMAGE_PROJECT },
	{ "image/heif", idhan::hydrus::gen_constants::IMAGE_HEIF },
	{ "image/heif-sequence", idhan::hydrus::gen_constants::IMAGE_HEIF_SEQUENCE },
	{ "image/heic", idhan::hydrus::gen_constants::IMAGE_HEIC },
	{ "image/heic-sequence", idhan::hydrus::gen_constants::IMAGE_HEIC_SEQUENCE },
	{ "image/avif", idhan::hydrus::gen_constants::IMAGE_AVIF },
	{ "image/avif-sequence", idhan::hydrus::gen_constants::IMAGE_AVIF_SEQUENCE },
	{ "unknown", idhan::hydrus::gen_constants::UNDETERMINED_GIF },
	{ "image/gif", idhan::hydrus::gen_constants::IMAGE_GIF },
	{ "unknown", idhan::hydrus::gen_constants::APPLICATION_PROCREATE },
	{ "image/qoi", idhan::hydrus::gen_constants::IMAGE_QOI },
	{ "application/epub+zip", idhan::hydrus::gen_constants::APPLICATION_EPUB },
	{ "image/vnd.djvu", idhan::hydrus::gen_constants::APPLICATION_DJVU },
	{ "application/vnd.comicbook+zip", idhan::hydrus::gen_constants::APPLICATION_CBZ },
	{ "unknown", idhan::hydrus::gen_constants::ANIMATION_UGOIRA },
	{ "application/rtf", idhan::hydrus::gen_constants::APPLICATION_RTF },
	{ "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	  idhan::hydrus::gen_constants::APPLICATION_DOCX },
	{ "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	  idhan::hydrus::gen_constants::APPLICATION_XLSX },
	{ "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	  idhan::hydrus::gen_constants::APPLICATION_PPTX },
	{ "unknown", idhan::hydrus::gen_constants::UNDETERMINED_OLE },
	{ "application/msword", idhan::hydrus::gen_constants::APPLICATION_DOC },
	{ "application/vnd.ms-excel", idhan::hydrus::gen_constants::APPLICATION_XLS },
	{ "application/vnd.ms-powerpoint", idhan::hydrus::gen_constants::APPLICATION_PPT },
	{ "image/webp", idhan::hydrus::gen_constants::ANIMATION_WEBP },
	{ "unknown", idhan::hydrus::gen_constants::UNDETERMINED_WEBP },
	{ "image/jxl", idhan::hydrus::gen_constants::IMAGE_JXL },
	{ "application/octet-stream", idhan::hydrus::gen_constants::APPLICATION_OCTET_STREAM },
	{ "unknown", idhan::hydrus::gen_constants::APPLICATION_UNKNOWN }
};