

# We start by getting the HydrusConstants.py file from the hydrus repo. This will be located in 3rd-party/hydrus

function(extract_constant_value CONSTANT_NAME OUTPUT_VARIABLE)
	file(STRINGS ${HYDRUS_CONSTANTS_FILE} FILE_CONTENTS)
	foreach (LINE ${FILE_CONTENTS})
		if (LINE MATCHES "^${CONSTANT_NAME}[ ]*=[ ]*([0-9]+)$")
			set(${OUTPUT_VARIABLE} ${CMAKE_MATCH_1} PARENT_SCOPE)
			break()
		endif ()
	endforeach ()
endfunction()

list(APPEND HYDRUS_CONSTANTS "TAG_REPOSITORY" "FILE_REPOSITORY" "LOCAL_FILE_DOMAIN" "MESSAGE_DEPOT" "LOCAL_TAG" "LOCAL_RATING_NUMERICAL" "LOCAL_RATING_LIKE" "RATING_NUMERICAL_REPOSITORY" "RATING_LIKE_REPOSITORY" "COMBINED_TAG" "COMBINED_FILE" "LOCAL_BOORU" "IPFS" "LOCAL_FILE_TRASH_DOMAIN" "COMBINED_LOCAL_FILE" "TEST_SERVICE" "LOCAL_NOTES" "CLIENT_API_SERVICE" "COMBINED_DELETED_FILE" "LOCAL_FILE_UPDATE_DOMAIN" "COMBINED_LOCAL_MEDIA" "LOCAL_RATING_INCDEC" "SERVER_ADMIN" "NULL_SERVICE")
list(APPEND HYDRUS_CONSTANTS "NETWORK_VERSION" "SOFTWARE_VERSION" "CLIENT_API_VERSION")
list(APPEND HYDRUS_CONSTANTS "STATUS_UNKNOWN" "STATUS_SUCCESSFUL_AND_NEW" "STATUS_SUCCESSFUL_BUT_REDUNDANT" "STATUS_DELETED" "STATUS_ERROR" "STATUS_NEW" "STATUS_PAUSED" "STATUS_VETOED" "STATUS_SKIPPED" "STATUS_SUCCESSFUL_AND_CHILD_FILES")
list(APPEND HYDRUS_CONSTANTS "SORT_FILES_BY_FILESIZE" "SORT_FILES_BY_DURATION" "SORT_FILES_BY_IMPORT_TIME" "SORT_FILES_BY_MIME" "SORT_FILES_BY_RANDOM" "SORT_FILES_BY_WIDTH" "SORT_FILES_BY_HEIGHT" "SORT_FILES_BY_RATIO" "SORT_FILES_BY_NUM_PIXELS" "SORT_FILES_BY_NUM_TAGS" "SORT_FILES_BY_MEDIA_VIEWS" "SORT_FILES_BY_MEDIA_VIEWTIME" "SORT_FILES_BY_APPROX_BITRATE" "SORT_FILES_BY_HAS_AUDIO" "SORT_FILES_BY_FILE_MODIFIED_TIMESTAMP" "SORT_FILES_BY_FRAMERATE" "SORT_FILES_BY_NUM_FRAMES" "SORT_FILES_BY_NUM_COLLECTION_FILES" "SORT_FILES_BY_LAST_VIEWED_TIME" "SORT_FILES_BY_ARCHIVED_TIMESTAMP" "SORT_FILES_BY_HASH" "SORT_FILES_BY_PIXEL_HASH" "SORT_FILES_BY_BLURHASH")
list(APPEND HYDRUS_CONSTANTS "SORT_ASC" "SORT_DESC")
list(APPEND HYDRUS_CONSTANTS "PAGE_TYPE_DUMPER" "PAGE_TYPE_IMPORT_MULTIPLE_GALLERY" "PAGE_TYPE_IMPORT_SIMPLE_DOWNLOADER" "PAGE_TYPE_IMPORT_HDD" "PAGE_TYPE_IMPORT_WATCHER" "PAGE_TYPE_PETITIONS" "PAGE_TYPE_QUERY" "PAGE_TYPE_IMPORT_URLS" "PAGE_TYPE_DUPLICATE_FILTER" "PAGE_TYPE_IMPORT_MULTIPLE_WATCHER" "PAGE_TYPE_PAGE_OF_PAGES")
list(APPEND HYDRUS_CONSTANTS "PAGE_STATE_NORMAL")
#list(APPEND HYDRUS_CONSTANTS "GENERAL_APPLICATION" "GENERAL_AUDIO" "GENERAL_IMAGE" "GENERAL_VIDEO" "GENERAL_ANIMATION" "GENERAL_APPLICATION_ARCHIVE" "GENERAL_IMAGE_PROJECT")
list(APPEND HYDRUS_CONSTANTS "APPLICATION_HYDRUS_CLIENT_COLLECTION" "IMAGE_JPEG" "IMAGE_PNG" "ANIMATION_GIF" "IMAGE_BMP" "APPLICATION_FLASH" "APPLICATION_YAML" "IMAGE_ICON" "TEXT_HTML" "VIDEO_FLV" "APPLICATION_PDF" "APPLICATION_ZIP" "APPLICATION_HYDRUS_ENCRYPTED_ZIP" "AUDIO_MP3" "VIDEO_MP4" "AUDIO_OGG" "AUDIO_FLAC" "AUDIO_WMA" "VIDEO_WMV" "UNDETERMINED_WM" "VIDEO_MKV" "VIDEO_WEBM" "APPLICATION_JSON" "ANIMATION_APNG" "UNDETERMINED_PNG" "VIDEO_MPEG" "VIDEO_MOV" "VIDEO_AVI" "APPLICATION_HYDRUS_UPDATE_DEFINITIONS" "APPLICATION_HYDRUS_UPDATE_CONTENT" "TEXT_PLAIN" "APPLICATION_RAR" "APPLICATION_7Z" "IMAGE_WEBP" "IMAGE_TIFF" "APPLICATION_PSD" "AUDIO_M4A" "VIDEO_REALMEDIA" "AUDIO_REALMEDIA" "AUDIO_TRUEAUDIO" "GENERAL_AUDIO" "GENERAL_IMAGE" "GENERAL_VIDEO" "GENERAL_APPLICATION" "GENERAL_ANIMATION" "APPLICATION_CLIP" "AUDIO_WAVE" "VIDEO_OGV" "AUDIO_MKV" "AUDIO_MP4" "UNDETERMINED_MP4" "APPLICATION_CBOR" "APPLICATION_WINDOWS_EXE" "AUDIO_WAVPACK" "APPLICATION_SAI2" "APPLICATION_KRITA" "IMAGE_SVG" "APPLICATION_XCF" "APPLICATION_GZIP" "GENERAL_APPLICATION_ARCHIVE" "GENERAL_IMAGE_PROJECT" "IMAGE_HEIF" "IMAGE_HEIF_SEQUENCE" "IMAGE_HEIC" "IMAGE_HEIC_SEQUENCE" "IMAGE_AVIF" "IMAGE_AVIF_SEQUENCE" "UNDETERMINED_GIF" "IMAGE_GIF" "APPLICATION_PROCREATE" "IMAGE_QOI" "APPLICATION_EPUB" "APPLICATION_DJVU" "APPLICATION_CBZ" "ANIMATION_UGOIRA" "APPLICATION_RTF" "APPLICATION_DOCX" "APPLICATION_XLSX" "APPLICATION_PPTX" "UNDETERMINED_OLE" "APPLICATION_DOC" "APPLICATION_XLS" "APPLICATION_PPT" "ANIMATION_WEBP" "UNDETERMINED_WEBP" "IMAGE_JXL" "APPLICATION_OCTET_STREAM" "APPLICATION_UNKNOWN")

# OUT_TARGET = file to write too

foreach (CONSTANT_NAME ${HYDRUS_CONSTANTS})
	extract_constant_value(${CONSTANT_NAME} ${CONSTANT_NAME})
endforeach ()

file(WRITE ${OUT_TARGET} "#pragma once\n")
file(APPEND ${OUT_TARGET} "#include <cstdint>\n\n")
file(APPEND ${OUT_TARGET} "namespace idhan::hydrus::gen_constants {\n\n")

foreach (CONSTANT_NAME ${HYDRUS_CONSTANTS})
	if (DEFINED ${CONSTANT_NAME})
		file(APPEND ${OUT_TARGET} "inline constexpr std::size_t ${CONSTANT_NAME} { ${${CONSTANT_NAME}} };\n")
	endif ()
endforeach ()

file(APPEND ${OUT_TARGET} "\n} // namespace idhan::hydrus::gen_constants\n")