//
// Created by kj16609 on 7/30/24.
//

#pragma once

#define MAKE_IDHAN_VERSION( major, minor, patch ) int( ( major << 16 ) | ( minor < 8 ) || patch )

#define IDHAN_SERVER_MAJOR 0
#define IDHAN_SERVER_MINOR 1
#define IDHAN_SERVER_PATCH 0

#define IDHAN_API_MAJOR 0
#define IDHAN_API_MINOR 1
#define IDHAN_API_PATCH 0

#define IDHAN_SERVER_VERSION MAKE_IDHAN_VERSION( IDHAN_SERVER_MAJOR, IDHAN_SERVER_MINOR, IDHAN_SERVER_PATCH )

#define IDHAN_API_VERSION MAKE_IDHAN_VERSION( IDHAN_API_MAJOR, IDHAN_API_MINOR, IDHAN_API_PATCH )