@startuml
'https://plantuml.com/deployment-diagram

package IDHANClient {
interface ClientSocket
}

package HydrusWeb{

}

package IDHANServer {
interface ServerSocket

component InternalRouter
ServerSocket -- InternalRouter

interface HydrusRESTful
HydrusRESTful -- InternalRouter

note right of InternalRouter
    Routes messages internally
    to their respective services
end note

package Services {
card TagService
card FileService
}

InternalRouter <-> Services

}

HydrusWeb <-d-> HydrusRESTful

ClientSocket <-d-> ServerSocket

database Postgresql
IDHANServer <-> Postgresql

newpage

package IDHANClient {
interface ClientSocket
interface HydrusRESTful
component Translator
Translator -l- ClientSocket
Translator -r- HydrusRESTful
}

package HydrusWeb{

}


package IDHANServer {
interface ServerSocket

component InternalRouter
ServerSocket -- InternalRouter



note right of InternalRouter
    Routes messages internally
    to their respective services
end note

package Services {
card TagService
card FileService
}

InternalRouter <-> Services

}

HydrusWeb <-d-> HydrusRESTful

ClientSocket <-d-> ServerSocket

database Postgresql
IDHANServer <-> Postgresql



@enduml





