if (CMAKE_BUILD_TYPE STREQUAL "System")
	set(CMAKE_BUILD_TYPE_BACKUP ${CMAKE_BUILD_TYPE})
	set(CMAKE_BUILD_TYPE "Release")
	add_subdirectory(${IDHAN_DEPENDENCIES}/libarchive ${CMAKE_CURRENT_BINARY_DIR}/libarchive)
	set(CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE_BACKUP})
	unset(CMAKE_BUILD_TYPE_BACKUP)
else ()
	add_subdirectory(${IDHAN_DEPENDENCIES}/libarchive ${CMAKE_CURRENT_BINARY_DIR}/libarchive)
endif ()
