#pragma once

#include "idhan/versions.hpp"

#define IDHAN_API_MAJOR 1
#define IDHAN_API_MINOR 0
#define IDHAN_API_PATCH 0

#define IDHAN_API_VERSION MAKE_IDHAN_VERSION( IDHAN_API_MAJOR, IDHAN_API_MINOR, IDHAN_API_PATCH )
