openapi: 3.0.0
servers:
  - url: /

info:
  description: Standard API for IDHAN
  version: "1.0.0"
  title: IDHAN API
  contact:
    email: kj16609@lolicon.zip
tags:
  - name: public
    description: Public access
  - name: tags
    description: Tag related operations
  - name: files
    description: File related operations

security:
  - KeyAuth: [ ]

paths:
  /version:
    $ref: './paths/version.yaml'
  /tag/create:
    $ref: './paths/tags/create.yaml'
  /tag/{tag_id}/info:
    $ref: './paths/tags/info.yaml'
  /tag/autocomplete:
    $ref: './paths/tags/autocomplete.yaml'
  /file/{file_id}/add_tag:
    $ref: './paths/file/add_tag.yaml'
  /file/{file_id}/tags:
    $ref: './paths/file/tags.yaml'
  /file/{file_id}/info:
    $ref: './paths/file/info.yaml'

components:
  schemas:
    TagInfo:
      $ref: './schemas/TagInfo.yaml'
    Version:
      $ref: './schemas/Version.yaml'
    VersionInfo:
      $ref: './schemas/VersionInfo.yaml'
    TagColor:
      $ref: './schemas/TagColor.yaml'
    TagSet:
      $ref: './schemas/TagSet.yaml'
    TagInput:
      $ref: './schemas/TagInput.yaml'
  securitySchemes:
    KeyAuth:
      $ref: './securitySchemes/KeyAuth.yaml'