name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: Get Conan
      # You may pin to the exact commit or the version.
      # uses: turtlebrowser/get-conan@4dc7e6dd45c8b1e02e909979d7cfc5ebba6ddbe2
      uses: turtlebrowser/get-conan@v1.0
    - name: Conan setup
      run: conan profile new default --detect
    - name: conan
      run: conan install --build=missing
    - name: make
      run: make
    - name : runTests
      run: ./bin/DBTest
