name: Automated Main Deploy Action
on:
  push:
    branches: [ master ]
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: (Doxygen) HTML
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "."

      - name: API Docs
        uses: Legion2/swagger-ui-action@v1.3.0
        with:
          output: './docs/html/swagger-ui'
          spec-file: "./docs/api.yaml"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: (Doxygen) Deploy HTML on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./docs/html"